apiVersion: v1
kind: Service
metadata:
  name: ssd-db-svc
  namespace: project-ns
spec:
  clusterIP: None # Headless Service
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: ssd-db
